---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: sim-runner
  namespace: keramik-anchor-polling-stops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sim-runner
  namespace: keramik-anchor-polling-stops
rules:
  - apiGroups:
      - keramik.3box.io
    resources:
      - networks
      - networks/status
      - simulations
      - simulations/status
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sim-runner
  namespace: keramik-anchor-polling-stops
subjects:
  - kind: ServiceAccount
    name: sim-runner
    namespace: keramik-anchor-polling-stops
roleRef:
  kind: Role
  name: sim-runner
  apiGroup: rbac.authorization.k8s.io
